
tame.catchExceptions ();

function foo (cb) {
    await setTimeout (defer (), 10);
    throw new Error ("oh no!")
    cb(10);
}

function bar (c) {
    await foo (defer ());
    c();
}

function baz () {
   await bar (defer ());
};

baz ();
